<a href="https://colab.research.google.com/github/tm8600-spec/Data-science-/blob/main/Data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.array([2,4,8])*3

array([ 6, 12, 24])

In [ ]:
a=np.array([1,6,8])
print(a)

[1 6 8]


In [ ]:
print(a.ndim)

1


In [ ]:
b=np.array([[1,3,9,4],[7,2,5,2]])
print(b.size)

8


In [ ]:
print(b.dtype)

int64


In [ ]:
print(b.shape)

(2, 4)


In [ ]:
print(b.itemsize)

8


In [ ]:
c=np.array(([1,3,5,4]),dtype=np.int32)
print(c)
print(c.itemsize)

[1 3 5 4]
4


In [ ]:
print(a[1])

6


In [ ]:
print(b.data)

In [ ]:
d=np.array([8,9,6,7,5,3,4])
d[3]=6
print(d)

[8 9 6 6 5 3 4]


In [ ]:
print(b)

[[1 3 9 4]
 [7 2 5 2]]


In [ ]:
print(b[1,1])

2


In [ ]:
a=np.ones(5)
print(a)

[1. 1. 1. 1. 1.]
